package jetbrains.rsynk.exit

object RsyncExitCodes {
  val SUCCESS = 0
  val SYNTAX_OR_USAGE_ERROR = 1
  val PROTOCOL_INCOMPATIBILITY = 2
  val ERROR_SELECTING_INPUT_FILES = 3
  val REQUESTED_ACTION_NOT_SUPPORTED = 4
  val ERROR_STARTING_SERVER_CLIENT_PROTOCOL = 5
  val ERROR_IN_SOCKET_IO = 10
  val ERROR_IN_FILE_IO = 11
  val ERROR_IN_RSYNC_PROTOCOL_DATA_STREAM = 12
}